name: Ejecutar Pruebas Gherkin con Behave

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install behave

    - name: Ejecutar pruebas Gherkin
      run: |
        behave --format=progress2 --junit

    - name: Generar informe HTML
      run: |
        behave --format=html -o reports

    - name: Notificar si las pruebas fallaron
      if: ${{ failure() }}
      run: echo "Las pruebas fallaron"

    - name: Subir informe HTML como artefacto
      uses: actions/upload-artifact@v2
      with:
        name: behave-reports
        path: reports
